# Generated by Django 5.0.7 on 2024-08-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("crm", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.DateField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="intmed_api.doctor",
                    ),
                ),
            ],
            options={
                "unique_together": {("doctor", "day")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleHour",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hour", models.TimeField()),
                ("isReserved", models.BooleanField(default=False)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules_hours",
                        to="intmed_api.schedule",
                    ),
                ),
            ],
            options={
                "unique_together": {("schedule", "hour")},
            },
        ),
    ]
