# Generated by Django 5.0.7 on 2024-08-07 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intmed_api", "0003_schedulehour_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Especialidade",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Médico", "verbose_name_plural": "Médicos"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Agenda", "verbose_name_plural": "Agendas"},
        ),
        migrations.AlterModelOptions(
            name="schedulehour",
            options={
                "verbose_name": "Horário da Agenda",
                "verbose_name_plural": "Horários da Agenda",
            },
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.DateField(verbose_name="Dia"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="intmed_api.doctor",
                verbose_name="Médico",
            ),
        ),
        migrations.AlterField(
            model_name="schedulehour",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_consult",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="schedulehour",
            name="hour",
            field=models.TimeField(verbose_name="Horário"),
        ),
        migrations.AlterField(
            model_name="schedulehour",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules_hours",
                to="intmed_api.schedule",
                verbose_name="Agenda",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="speciality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specialities",
                to="intmed_api.speciality",
                verbose_name="Especialidade",
            ),
        ),
    ]
