# Generated by Django 5.0.7 on 2024-08-07 14:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intmed_api", "0004_speciality_alter_doctor_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TimeField(),
                default=list,
                size=None,
                verbose_name="Horários Disponíveis",
            ),
        ),
        migrations.CreateModel(
            name="Consult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hour", models.TimeField(verbose_name="Horário")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consult",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="intmed_api.schedule",
                        verbose_name="Agenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "unique_together": {("schedule", "hour")},
            },
        ),
        migrations.DeleteModel(
            name="ScheduleHour",
        ),
    ]
