# Generated by Django 5.0.7 on 2024-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intmed_api", "0005_schedule_hours_consult_delete_schedulehour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="crm",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
