# Generated by Django 5.0.7 on 2024-08-08 02:19

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intmed_api", "0006_alter_doctor_crm"),
    ]

    operations = [
        migrations.AddField(
            model_name="consult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TimeField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Horários Disponíveis",
            ),
        ),
    ]
